apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laurenssvg/homelab-gitops.git
    targetRevision: main
    path: clusters/home/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
